language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: "timothy.dunphy@gmail.com"
  api_key: "$NPM_TOKEN"
after_success:
- bash <(curl -s https://codecov.io/bash)